version: "3.8"
services:
  bouncer-unifi:
    image: ghcr.io/teifun2/cs-unifi-bouncer:latest
    container_name: bouncer-unifi
    environment:
      CROWDSEC_BOUNCER_API_KEY: MyApiKey
      CROWDSEC_URL: "http://crowdsec:8080/"
      UNIFI_HOST: "https://yourunifi:443"
      UNIFI_USER: "api"
      UNIFI_PASS: "password"
      # Only use this if your unifi instance does not have a proper certificate.
      # UNIFI_SKIP_TLS_VERIFY: "true"
    restart: unless-stopped
